version: 2.1

executors:
  # Define a Python executor using a pre-built CircleCI image.
  # This image comes with Python pre-installed.
  python-executor:
    docker:
      - image: cimg/python:3.10

jobs:
  test_pypi_publish:
    executor: python-executor
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install dependencies
          command: |  
            uv sync
      - run:
          name: Package
          command: |
            uv build
      - run:
          name: Publish to Test PyPI
          command: |
            uv publish -- --index testpypi dist/*


  pypi_publish:
    executor: python-executor
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install dependencies
          command: |  
            uv sync
      - run:
          name: Package
          command: |
            uv build
      - run:
          name: Publish to PyPI
          command: |
            uv publish

workflows:
  build_test_publish:
    jobs:
      - test_pypi_publish:
          context: python_twine
          filters:
            branches:
              only:
                - develop
      - pypi_publish:
          context: python_twine
          filters:
            branches:
              only:
                - master